import { getModelPricing, costComponent } from "@nullspend/cost-engine";
import type { NewCostEventRow } from "@nullspend/db";
import type { OpenAIUsage } from "./sse-parser.js";
import { emitMetric } from "./metrics.js";

/** Fields auto-generated by the database — excluded from the insert type. */
type CostEventInsert = Omit<NewCostEventRow, "id" | "createdAt">;

/**
 * Map an OpenAI usage object to a cost event ready for persistence.
 *
 * Returns a {@link CostEventInsert} that satisfies `logCostEvent`'s parameter
 * type, making the cost-engine → DB type contract explicit at compile time.
 *
 * Looks up pricing by requestModel first (matches our "openai/gpt-4o" keys).
 * Falls back to responseModel (OpenAI may resolve aliases like gpt-4o → gpt-4o-2024-11-20).
 */
export function calculateOpenAICost(
  requestModel: string,
  responseModel: string | null,
  usage: OpenAIUsage,
  requestId: string,
  durationMs: number,
  attribution?: { userId: string | null; apiKeyId: string | null; actionId: string | null },
  toolDefinitionTokens?: number,
): CostEventInsert {
  const promptTokens = Math.max(0, Number(usage.prompt_tokens) || 0);
  const completionTokens = Math.max(0, Number(usage.completion_tokens) || 0);
  const rawCachedTokens = Math.max(0, Number(usage.prompt_tokens_details?.cached_tokens) || 0);
  const reasoningTokens = Math.max(0, Number(usage.completion_tokens_details?.reasoning_tokens) || 0);

  // P0-6: OpenAI's documented invariant is `cached_tokens <= prompt_tokens`
  // (cached is a subset of prompt). Without a defensive clamp, malformed
  // upstream usage with inverted counts would push `normalInputTokens`
  // negative. `costComponent` treats negative token counts as 0, so the
  // "normal input" cost would silently vanish while `cached` still charges
  // at its (lower) rate — a massive undercharge. Mirror gemini's clamp
  // (gemini-cost-calculator.ts:50-55) and emit a metric when the invariant
  // violation actually fires so upstream bugs become observable.
  const cachedTokens = Math.min(rawCachedTokens, promptTokens);
  if (rawCachedTokens > promptTokens) {
    emitMetric("cost_calc_cached_gt_prompt", {
      provider: "openai",
      model: requestModel,
      rawCachedTokens,
      promptTokens,
    });
  }

  const normalInputTokens = promptTokens - cachedTokens;

  let pricing = getModelPricing("openai", requestModel);
  let resolvedModel = requestModel;

  if (!pricing && responseModel) {
    pricing = getModelPricing("openai", responseModel);
    if (pricing) resolvedModel = responseModel;
  }

  let costMicrodollars = 0;
  let costBreakdown: CostEventInsert["costBreakdown"] = null;
  if (pricing) {
    const input = costComponent(normalInputTokens, pricing.inputPerMTok);
    const cached = costComponent(cachedTokens, pricing.cachedInputPerMTok);
    const output = costComponent(completionTokens, pricing.outputPerMTok);
    costMicrodollars = Math.max(0, Math.round(input + cached + output));

    // Round components, then distribute rounding residual to largest to guarantee exact sum
    const roundedInput = Math.round(input);
    const roundedCached = Math.round(cached);
    const roundedOutput = Math.round(output);
    const residual = costMicrodollars - (roundedInput + roundedCached + roundedOutput);
    let adjInput = roundedInput;
    let adjCached = roundedCached;
    let adjOutput = roundedOutput;
    if (residual !== 0) {
      // Apply residual to the largest component
      if (output >= input && output >= cached) adjOutput += residual;
      else if (input >= cached) adjInput += residual;
      else adjCached += residual;
    }
    const bd: { input: number; output: number; cached: number; reasoning?: number; toolDefinition?: number } = {
      input: adjInput, output: adjOutput, cached: adjCached,
    };

    // Reasoning is a SUBSET of output cost (already counted in output), stored for informational display
    if (reasoningTokens > 0) {
      bd.reasoning = Math.round(costComponent(reasoningTokens, pricing.outputPerMTok));
    }

    // Tool definition is a SUBSET of input cost (already counted in prompt_tokens), stored for attribution
    if (toolDefinitionTokens && toolDefinitionTokens > 0) {
      bd.toolDefinition = Math.round(costComponent(toolDefinitionTokens, pricing.inputPerMTok));
    }

    costBreakdown = bd;
  }

  return {
    requestId,
    provider: "openai",
    model: resolvedModel,
    inputTokens: promptTokens,
    outputTokens: completionTokens,
    cachedInputTokens: cachedTokens,
    reasoningTokens,
    costMicrodollars,
    costBreakdown,
    durationMs,
    userId: attribution?.userId ?? null,
    apiKeyId: attribution?.apiKeyId ?? null,
    actionId: attribution?.actionId ?? null,
    eventType: "llm" as const,
  };
}
